Print out healthcare section
ministryofjustice/moving-people-safely pull request #242
Opened 2017-03-03 16:19 UTC by lostie

[Trello](https://trello.com/c/jipJ5uDK/32-5-as-someone-printing-out-a-completed-digital-per-i-want-to-see-a-summary-of-all-the-healthcare-information-in-the-printed-sheet)

Add healthcare assessment content to the move printout.

As an additional part of this PR I've engaged in some extra work to try to simplify the way the assessments information is managed and displayed:

- Destructure assessments information into a more OO approach
- Add an assessment description file that contains all the information
for all the existent assessments: risk and healthcare
- Load the assessment description file and instantiate objects that
contain the information related with the assessment

Right now there's 2 main objects:
- Section - contains a group of questions
- Question - contains all the informations related with a given question

Refactored the print presentation for the assessments to make use of
this new approach.

- Update wording for Assessments summary/printout content

2017-03-06 13:50 UTC, dan-palmer requested changes
Its probably worth putting something into the Readme discussing the whole assessments shema. Just that its a thing, how & why sorta deal.

2017-03-06 13:50 UTC, dan-palmer commented on app/models/assessments/question.rb
> +      return false if relevant_answers.empty? || !answer.present?
How about: `answer.blank?`

2017-03-06 13:50 UTC, dan-palmer commented on app/models/assessments/question.rb
> +      !dependencies.empty?
How about: `dependencies.present?`

2017-03-06 13:50 UTC, dan-palmer commented on app/presenters/print/risk_presenter.rb
> -module Print
🚶 👋 🚪

2017-03-06 13:51 UTC, dan-palmer commented on app/models/assessments/question.rb
> +      !dependencies.empty?
There are a couple more of these as well.

2017-03-07 10:31 UTC, lostie commented
♻️

2017-03-07 12:23 UTC, dan-palmer commented on app/models/assessments/section.rb
> +      !subsections.empty?
& another chap here

2017-03-07 14:56 UTC, dan-palmer approved these changes

2017-03-07 14:59 UTC, merged